name: hotel_management
description: hotel management for CSE3010

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  flutter_spinkit: ^4.1.2+1
  flutter_rounded_date_picker: 1.0.5
  auto_size_text_field: ^0.1.7
  buttons_tabbar: ^1.0.2+1
  flutter_animated_dialog: ^1.2.0
  flutter_slidable: ^0.5.7
  sliding_up_panel: ^1.0.2
  percent_indicator: ^2.1.8
  flutter_login: ^1.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/b_hotel_icon.png

  fonts:
    - family: Godo-B
      fonts:
        - asset: fonts/GodoB.ttf
    - family: Godo-M
      fonts:
        - asset: fonts/GodoM.ttf
